### ISSUE TITLE
ETLEGACY NOT WORK

### ISSUE THREAD

**Issue by Robotec53** [Ch40zz/CCHookReloaded#10]
I did all the steps of the last installer and nothing

**Comment by Robotec53** [comment]
I sent you a DM on Twitter

**Comment by Ch40zz** [comment]
The cheat works fine also on Legacy 2.82.1. Are you using the 32 bit version? 64 bit isnt supported. Do you get any error or any output? Please compile the newest version instead of using the old releases

**Comment by Robotec53** [comment]
> The cheat works fine also on Legacy 2.82.1. Are you using the 32 bit version? 64 bit isnt supported. Do you get any error or any output? Please compile the newest version instead of using the old releases

I use 64-bit windows and errors occur. If you could help me get it working, I would be extremely grateful.

In the most updated file you uploaded, is visual studio also required?

**Comment by Robotec53** [comment]
https://github.com/Ch40zz/CCHookReloaded/releases/tag/v1.1.0 this

**Comment by Ch40zz** [comment]
> > The cheat works fine also on Legacy 2.82.1. Are you using the 32 bit version? 64 bit isnt supported. Do you get any error or any output? Please compile the newest version instead of using the old releases
> 
> I use 64-bit windows and errors occur. If you could help me get it working, I would be extremely grateful.
> 
> In the most updated file you uploaded, is visual studio also required?

Im talking about the version of the game not your OS. You need to use the 32 bit version of ET Legacy: https://www.etlegacy.com/download/file/595
And yes you need visual studio to compile the code, however what you linked is an already compiled package and will work just as is.

**Comment by Robotec53** [comment]
> > > The cheat works fine also on Legacy 2.82.1. Are you using the 32 bit version? 64 bit isnt supported. Do you get any error or any output? Please compile the newest version instead of using the old releases
> > 
> > 
> > I use 64-bit windows and errors occur. If you could help me get it working, I would be extremely grateful.
> > In the most updated file you uploaded, is visual studio also required?
> 
> Im talking about the version of the game not your OS. You need to use the 32 bit version of ET Legacy: https://www.etlegacy.com/download/file/595 And yes you need visual studio to compile the code, however what you linked is an already compiled package and will work just as is.

Ok, follow those steps and now I get another error:

"LDRLOADDLL WAS UNSUCCESSFUL AND RETURNED STATUS"

**Comment by Robotec53** [comment]
After all this, I would like to know how to not be detected, what would be the best way?

**Comment by Robotec53** [comment]
If you give me your discord, I can show you on anydesk

**Comment by Ch40zz** [comment]
Try the new release: https://github.com/Ch40zz/CCHookReloaded/releases/tag/v1.2.0

**Comment by Robotec53** [comment]
now it works 100%. I want to know about configurations, do you think we can talk in pm?

**Comment by Ch40zz** [comment]
> now it works 100%. I want to know about configurations, do you think we can talk in pm?

Great :) I will message you later. Closed as working due to new release
