### ISSUE TITLE
how do you safely debug a custom AC

### ISSUE THREAD

**Issue by tooor** [Ch40zz/CCHookReloaded#12]
first of all, sorry to contact you like this and thank you very much for this project.

**background:**
a server implemented their own .dll called **my_cgame_mp_x86.dll** which, i assume, is monitoring the real cgame_mp_x86.dll for hooks, etc. the confusing thing is their function table looks a lot like the regular cgame.dll, with it's own _vmmain and all. 

**questions:**
how would you go about finding the functions to hook in their .dll?

when you're doing testing/development, are you starting a local server with a given mod/real server config and reverse it locally? or do you have to run et.exe in a debugger, connect to server, and be ready to HWID spoof if banned?

thanks again.

**Comment by Ch40zz** [comment]
Hey, thanks for your praise! Sorry it took me a while to reply, I was quite sick :(
  
> the confusing thing is their function table looks a lot like the regular cgame.dll, with it's own _vmmain and all.

well that makes sense to me, they probably proxy all calls from their own cgame to the real mods cgame as some anti cheat measure. I remember seeing that yet it never caused any detections or problems on my side at all.
  

> how would you go about finding the functions to hook in their .dll?

your best bet is a mixed approach to do static analysis using IDA until you get stuck and then switch to dynamic analysis with a debugger to confirm certain findings and find new starting points for static analysis.
  

> when you're doing testing/development, are you starting a local server with a given mod/real server config and reverse it locally? or do you have to run et.exe in a debugger, connect to server, and be ready to HWID spoof if banned?

generally I'd try to always look at my code and fix all the things I would detect myself as an AC.
if you still have detections after that now its time to reverse the AC, never do that beforehand unless youre out of ideas.

if its a custom AC I just connect to the server and do my thing, however if its built into the mod I usually start my own local server.
if youre unsure its best to just always connect to the real server.

**Comment by Ch40zz** [comment]
FYI I checked Fearless Assassins server and they do this thing, however your initial assumption is wrong. ``my_cgame_mp_x86.dll`` is the unmodified mod DLL while the ``cgame_mp_x86.dll`` is their anti cheat. They use some sort of protector to apply opaque predicates on their binary, nothing that really stops experienced enough people but I assume most hobby reverse engineers will have some bigger issues with it. Didnt play too much with it yet however the DLL is really small and is crosscompiled with GCC via MINGW for Windows. Very odd dev environment but okay. 

EDIT:
Had a quick look and their opaque predicates are a pretty big meme. Basically it can be distilled to this:
```
E8 01 00 00 00		call V
??			Filler jumped
58			pop eax
85 C0			test eax, eax
7? ??			jz ??
?????????????????????????????????????????
8D 05 ? ? ? ?		lea eax, ???
50 C3			push eax; ret // jmp eax
```
I'll prob write a python script at some point to clean this up in an automated way

**Comment by Ch40zz** [comment]
I'm sadly a bit out of time again at the moment but I will add some custom code for F|A servers at some point when I find more time again :)
I'm closing this for now, hope my answers somehow helped you!
