### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by amorimnuno** [Ch40zz/CCHookReloaded#13]
Getting error
LdrLoadDll was unsuccessful and returned status 0xC0000142

**Comment by Ch40zz** [comment]
Did you compile the newest source or are you using the last released binaries?
The new ETL version is not supported by the last release, please compile the cheat yourself or use an older ETL version

**Comment by amorimnuno** [comment]
ohh ok  ty

**Comment by amorimnuno** [comment]
Loaded CCHook:Reloaded! Make sure to undefine `USE_DEBUG` for release builds.
[WARNING] Failed to recognize 'et.exe' version. Defaulting to dynamic offsets.
Waiting for game...

**Comment by Ch40zz** [comment]
Which version of the code and what version of ET are you trying to use?

**Comment by Ch40zz** [comment]
Any recent developments on this?

**Comment by Ch40zz** [comment]
Any news on this? Will assume it is fixed and close this soon
