### ISSUE TITLE
Trolling

### ISSUE THREAD

**Issue by emanonKID** [Ch40zz/CCHookReloaded#14]
I pub enemy territory. Some players hack and it's obvious. Playing against hacks makes me very frustrated. I was told by a teammate that it's CCHook and they all have Discord and laugh about it. I wanted to Discord w/you to find that player who was laughing about hacking us - to catch him in the act. 

Since then, I have spoken w/ a peer of mine and he convinced me otherwise. That he doesn't hack and that it's been a long time since I played ET. That Jaymod has large headshot boxes and that lag on Jaymod is broken.

**Comment by emanonKID** [comment]
Many old-school ET players on Discord were aware I went active again. One, who after searching my name and looking for any connections to hacks, found your Youtube/CCHack video and mocked and ridiculed me for asking to Discord w/ you. They all put their hands to their forehead and turned their backs to me.

**Comment by Ch40zz** [comment]
Hm, I'm sorry that happened to you but shouldn't they know whether you are actually using cheats or not? Why do they take such a weak indicator that serious? Pretty sad :(

**Comment by emanonKID** [comment]
Thanks. They don't care. All of us were professional gamers at one time or another. What hurts is the strong feeling of betrayal/shame. The people you thought you could trust now mock you or block you and leave you to die.

ET had its day in the sun. ET is now an ancient game w/ low appeal, low number of players, low platform playability - PC only, no console/phone/tablet support - and no plan to reach out for new players. 

You truly see if a person has character when they're unaware that you can see them, and when that person judges you. Even if I hadn't asked you for Discord, how they used it against me tells me who they really are. Do I really want to game w/ a group of people who fly like vultures and swim like a big fish in a small pond?

**Comment by Ch40zz** [comment]
I fully agree, probably for the best. Still sucks that it had to be this way :(
