### ISSUE TITLE
Aimbot lag

### ISSUE THREAD

**Issue by AieCaramba** [Ch40zz/CCHookReloaded#2]
Hello,
I tested it but when I play on a server where there is more than 10vs10, when I shoot with the aimbot, I have the fps going from 166 to 25... Would it be possible to correct this?

**Comment by Ch40zz** [comment]
I noticed some FPS loss on very busy servers, especially when multiple explosions are present.
Do you maybe have any more details on when exactly you have FPS issues so I can reproduce the issue?
For example does it only happen when the aimbot is aiming at a player, or does it happen when you press the aimkey but not even a single player is visible or does it happen when you have autoshoot enabled?
It might be the visible check that does hitgox boundary checks. If its that I could add a less accurate but faster visible check method for you.
What CPU do you use? is your machine specifically old or slow?

**Comment by AieCaramba** [comment]
Hello,
it's only when I use the human aim at that I play on a server where there are 15 players vs 15 players.
And it's when i press aimkey :)

and i just press one time , it's go 166fps to 20...
and when i keyup it's go back to 166

I have an i7 9700k with a 2060super and 32go ram...

**Comment by Ch40zz** [comment]
Made it possible to adapt the aimbot trace-box step size in commit f2319ac51a09236c80c9ff66321ae873ec4094c5.
Default values have been increased to 0.5 and 0.3 from 0.1 each which results in significantly less traces.
Of course the visible checks are now less accurate, you can always configure the accuracy by changing the step size in ``config.h``.
The new values are named ``aimbotHeadBoxTraceStep`` and ``aimbotBodyBoxTraceStep``.
