### ISSUE TITLE
Clean screenshot

### ISSUE THREAD

**Issue by AieCaramba** [Ch40zz/CCHookReloaded#3]
Hello,
I have tested the clean screenshot on nitmod 2.3.4 but the clean screenshot does not work.

Unfortunately Nitrox is active so I don't think it will ever work as they update the mod regularly.

Is there still a fix possible?

**Comment by Ch40zz** [comment]
Can you give more details on how to specifically test the nitmod screenshot implementation?
I assume they take the screenshot with their mod? I would assume they have OS specific code to grab screenshots from a window maybe (e.g. using BitBlt). If you play fullscreen they HAVE to fallback to opengl.

**Comment by AieCaramba** [comment]
They use the !ss command
And then the screenshot appears in the nitmod folder with a .jpg

You should try this by creating a local server.

**Comment by Ch40zz** [comment]
Alright, I took a few minutes to reverse engineer their mod and found the code that is responsible for sending the screenshot.
They send a command called ``getss`` to the client containing the value of the jpeg quality.
They call glReadPixels like this:
```cpp
glFlush();
glFinish();
glReadPixels(0, 0, ScreenResY, ScreenResX, 6408, 5121, PixelData);
...
mozjpeg_compress(PixelData, ScreenResX, ScreenResY, nx_jpegQuality, &JpegDataOutSize, &JpegDataOut);
```
This should definitely get picked up by the hook and filtered on the client.
Can you please validate that using the ``/screenshot`` command creates a clean screenshot for you?
You can enable the ``USE_DEBUG`` macro and it should print ``glReadPixels: Screenshot requested! Blocking...`` into the console.

EDIT: It seems like one of the older commits actually broke this without me noticing, will immediately fix

**Comment by Ch40zz** [comment]
Issue has been fixed in 4c4ee121c43b109fa5fbab9a9d21685fabcfb4f9.

**Comment by AieCaramba** [comment]
I try with:
/screenshot => i got the msg in the command => i see the wh on the screenshot
!ss => same

**Comment by AieCaramba** [comment]
Ah ok u close the issue , thx bro :)
