### ISSUE TITLE
Cod implementation  

### ISSUE THREAD

**Issue by swisscheez2** [Ch40zz/CCHookReloaded#6]
This is more of a personal question than anything else.

I've only glanced at the project so far, hence why I'm asking. how easy would you think could one use this on the cod series?. Afaik it uses quake as a base. I guess since cod1 is OpenGL this might be the easiest one to implement given the similarity.

I really like the idea since I've never seen somebody hook the vm before seeing this git.

**Comment by Ch40zz** [comment]
Hey,
That really depends. If the CoD game in question utilizes the VM concept then this method most likely can be used.
This is probably true up until CoD 4 (IW 3.0) but not for later versions (especially not the modern IW 9.0 releases). I didn't really work on old CoD games so take this info with a grain of salt :P
