### ISSUE TITLE
SpecWarn not working

### ISSUE THREAD

**Issue by Grimbeert-DeDas** [Ch40zz/CCHookReloaded#9]
warn isnt working

**Comment by Ch40zz** [comment]
Any more Infos than "not working"?
Any specific mod or server? The feature doesnt work on all mods.

**Comment by Grimbeert-DeDas** [comment]
not working on legacy

**Comment by Ch40zz** [comment]
Fixed in https://github.com/Ch40zz/CCHookReloaded/commit/3e79c43e719bd6659f102c544aa4fd88af4b3ef4, can you please test and let me know if it is all working now?

**Comment by Grimbeert-DeDas** [comment]
Not working, only shows your own name in spec, it doesnt do anything when join team.  I had some friend spec me and I didnt saw the warning.

**Comment by Grimbeert-DeDas** [comment]
anti screen shake not work too 
what is latest version of legacy supported?

**Comment by Ch40zz** [comment]
The cheat was made for the original version of ET and due to heavy request I simply ported it to legacy. Some features may not work correctly because of that however I can look into it. Newest legacy should be supported

**Comment by Robotec53** [comment]
> anti screen shake not work too what is latest version of legacy supported?

Legacy is currently at 2.82. How did you do the injection?

**Comment by Ch40zz** [comment]
> Not working, only shows your own name in spec, it doesnt do anything when join team. I had some friend spec me and I didnt saw the warning.

Legacy mod does not support spectator warning as the XP numbers of a player are not inherited when spectating someone.
This only works on older mods and etmain.



> anti screen shake not work too what is latest version of legacy supported?

The latest version of legacy (2.82.1) is supported, I just tested no camera shake on explosions and it works perfectly fine

**Comment by Grimbeert-DeDas** [comment]
Ye works on 82.1 
the warn would be gud if work possible

**Comment by Ch40zz** [comment]
> Ye works on 82.1 the warn would be gud if work possible

The game architecture does not really allow for knowing who is spectating you.
We abuse a known quirk of some of the mods to make it work, if a mod doesn't behave like this it is sadly impossible to have spec warn for that mod. I can try a few other things and see if I can come up with another trick to do it but I have my doubts.

Closing this for now as e verything has been resolved, thanks for reporting
